# Generated by Django 5.2.4 on 2025-07-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('structured', 'Structured')], default='text', max_length=20),
        ),
    ]
