# Generated by Django 5.2.4 on 2025-08-01 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_book_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStructuredData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(default='Sheet1', max_length=100)),
                ('row_index', models.IntegerField()),
                ('column_name', models.TextField()),
                ('value', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookapp.book')),
            ],
        ),
    ]
