# Generated by Django 5.2.4 on 2025-08-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_bookstructureddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
