# Generated by Django 5.2.4 on 2025-08-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_alter_book_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('structured', 'Structured'), ('website', 'Website')], default='text', max_length=20),
        ),
    ]
